[package]
name = "hypervisor-hcs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
hypervisor-api = { workspace = true }
vm-model       = { workspace = true }
error-stack    = { workspace = true }
tracing        = { workspace = true, optional = true }
uuid           = { workspace = true, features = ["v4"] }
sha2           = { workspace = true }

[features]
tracing = ["dep:tracing"]

[target.'cfg(target_os = "windows")'.dependencies]
tokio-util = { workspace = true }
tokio      = { workspace = true, features = ["windows-sys"] }
serde      = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
redb       = { workspace = true }

[dev-dependencies]
escargot = "0.5"

