[package]
name = "jyth-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
vm-model       = { workspace = true }
hypervisor-api = { workspace = true }
scheduler      = { workspace = true }
guest-client   = { workspace = true }
protocol       = { workspace = true }

tokio          = { workspace = true }
tokio-util     = { workspace = true }
error-stack    = { workspace = true }
tracing        = { workspace = true, optional = true }
thiserror      = { workspace = true }
uuid           = { workspace = true }

[features]
tracing = ["dep:tracing"]

[dev-dependencies]
